import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { getUserAccess } from "@/lib/auth/get-user-access";
import { assertVisitReportAccess } from "@/lib/visits/visit-report-access";

const BUCKET = "medical-files";

/**
 * Serves the visit report PDF **only** after it has been generated by saving the visit
 * (stored in `visit_report_pdf_path`). No on-the-fly generation — avoids download before clinical save.
 */
export async function GET(_request: Request, { params }: { params: { id: string } }) {
  const access = await getUserAccess();
  const supabase = createClient();
  try {
    await assertVisitReportAccess(supabase, access, params.id);
  } catch (e) {
    const msg = e instanceof Error ? e.message : "Forbidden";
    return NextResponse.json({ error: msg }, { status: 403 });
  }

  const { data: visit, error: vErr } = await supabase
    .from("visits")
    .select("visit_report_pdf_path")
    .eq("id", params.id)
    .maybeSingle();

  if (vErr || !visit?.visit_report_pdf_path?.trim()) {
    return NextResponse.json(
      {
        error:
          "This report is not available yet. The clinician must save the visit (Save entire visit) to generate the PDF.",
      },
      { status: 404 },
    );
  }

  const path = visit.visit_report_pdf_path.trim();
  const { data: blob, error: dlErr } = await supabase.storage.from(BUCKET).download(path);
  if (dlErr || !blob) {
    return NextResponse.json(
      { error: "Report file is missing from storage. Save the visit again to regenerate it." },
      { status: 404 },
    );
  }

  const bytes = await blob.arrayBuffer();
  return new NextResponse(bytes, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="visit-report-${params.id.slice(0, 8)}.pdf"`,
      "Cache-Control": "private, no-store",
    },
  });
}
