import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f6fafe",
        foreground: "#171c1f",
        /** Legacy shadcn-style tokens used on store/account pages */
        muted: {
          DEFAULT: "#eaeef2",
          foreground: "#3d4a43",
        },
        "muted-foreground": "#3d4a43",
        "outline-variant": "#bbcac1",
        "on-surface": "#171c1f",
        "on-surface-variant": "#3d4a43",
        "on-error": "#ffffff",
        "surface-variant": "#dfe3e7",
        "on-secondary-fixed": "#111c2d",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-background": "#171c1f",
        "tertiary-fixed": "#ffdeae",
        primary: "#006c50",
        "on-secondary-container": "#586377",
        "surface-container": "#eaeef2",
        "secondary-fixed": "#d8e3fb",
        tertiary: "#7f5600",
        "secondary-fixed-dim": "#bcc7de",
        "on-primary-container": "#004c37",
        "inverse-on-surface": "#edf1f5",
        "on-primary-fixed-variant": "#00513b",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#002116",
        "surface-container-high": "#e4e9ed",
        "surface-bright": "#f6fafe",
        "surface-dim": "#d6dade",
        "tertiary-fixed-dim": "#ffba3f",
        "inverse-surface": "#2c3134",
        "secondary-container": "#d5e0f8",
        "on-secondary": "#ffffff",
        "tertiary-container": "#e8a100",
        "inverse-primary": "#56ddae",
        "error-container": "#ffdad6",
        outline: "#6c7a73",
        "on-tertiary-container": "#5a3c00",
        "on-tertiary": "#ffffff",
        secondary: "#545f73",
        "surface-container-highest": "#dfe3e7",
        "primary-container": "#36c497",
        "on-tertiary-fixed-variant": "#604100",
        "surface-tint": "#006c50",
        "on-tertiary-fixed": "#281800",
        "surface-container-low": "#f0f4f8",
        surface: "#f6fafe",
        "primary-fixed-dim": "#56ddae",
        "on-secondary-fixed-variant": "#3c475a",
        "on-error-container": "#93000a",
        "primary-fixed": "#75fac9",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        clinical: "0 12px 32px rgba(23, 28, 31, 0.06)",
      },
    },
  },
  plugins: [],
};
export default config;
